#!/bin/sh

echo "\n\n"
echo "Fetching BI json Addresses"
echo "GiveDirect.BI*interstellar.exchange"
echo "DEPOSIT_ACCOUNT_BI = GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT"
echo "---------------------"
wget -q --show-progress -O BI.BTC.GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT.json 'http://cryptoanchor.io/stellar/deposit?asset_code=BTC&account=GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT'
wget -q --show-progress -O BI.LTC.GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT.json 'http://cryptoanchor.io/stellar/deposit?asset_code=LTC&account=GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT'
wget -q --show-progress -O BI.ETH.GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT.json 'http://cryptoanchor.io/stellar/deposit?asset_code=ETH&account=GDHEWO2WAM6MFHPUHRZWCN3AWLW2BWXQU3VE67CLT5WVYGI6DSME24FT'

echo "\n\n"
echo "Fetching Data json Addresses"
echo "GiveDirect.Data*interstellar.exchange"
echo "DEPOSIT_ACCOUNT_DATA = GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK"
echo "---------------------"
wget -q --show-progress -O DATA.BTC.GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=BTC&account=GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK'
wget -q --show-progress -O DATA.LTC.GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=LTC&account=GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK'
wget -q --show-progress -O DATA.ETH.GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=ETH&account=GAHAITQRFJWCVIVFFD3WBBOIJWUVCXWG3NL4VWNT42UFU37O57ZXPEJK'

echo "\n\n"
echo "Fetching Comm json Addresses"
echo "GiveDirect.Comm*interstellar.exchange"
echo "DEPOSIT_ACCOUNT_COMM = GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6"
echo "---------------------"
wget -q --show-progress -O COMM.BTC.GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6.json 'http://cryptoanchor.io/stellar/deposit?asset_code=BTC&account=GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6'
wget -q --show-progress -O COMM.LTC.GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6.json 'http://cryptoanchor.io/stellar/deposit?asset_code=LTC&account=GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6'
wget -q --show-progress -O COMM.ETH.GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6.json 'http://cryptoanchor.io/stellar/deposit?asset_code=ETH&account=GAKI3PEDQVEC4KQXFKUDPC5UUU5IQKB6BE2ZB6M2JHS6VMNDH3TZCFT6'

echo "\n\n"
echo "Fetching Condom json Addresses"
echo "GiveDirect.Condom*interstellar.exchange"
echo "DEPOSIT_ACCOUNT_CONDOM = GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA"
wget -q --show-progress -O CONDOM.BTC.GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA.json 'http://cryptoanchor.io/stellar/deposit?asset_code=BTC&account=GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA'
wget -q --show-progress -O CONDOM.LTC.GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA.json 'http://cryptoanchor.io/stellar/deposit?asset_code=LTC&account=GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA'
wget -q --show-progress -O CONDOM.ETH.GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA.json 'http://cryptoanchor.io/stellar/deposit?asset_code=ETH&account=GCPHJIS7D7BFSBS3BQZ6PMDZSBAMPTFAPPHCGNXC7DBMQUKZCWTQF7FA'

echo "\n\n"
echo "Fetching Hardware json Addresses"
echo "GiveDirect.HW*interstellar.exchange"
echo "DEPOSIT_ACCOUNT_HW = GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK"
wget -q --show-progress -O HW.BTC.GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=BTC&account=GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK'
wget -q --show-progress -O HW.LTC.GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=LTC&account=GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK'
wget -q --show-progress -O HW.ETH.GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK.json 'http://cryptoanchor.io/stellar/deposit?asset_code=ETH&account=GC4VKHM2YARIPJAPWBNVYRG45FS7L5HAP6ZWTM23H4ATS6EHRM6HQ6NK'

echo "\n\n"
echo "Moving to HTML file Generation (gd-json-to-html.py)..."
echo "---------------------"
./gd-json-to-html.py

echo "\n\n"
echo "Removing json files..."
echo "---------------------"
rm ./*.json

